# Generated by Django 4.1.1 on 2023-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=4)),
                ('last_name', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stocks',
        ),
    ]
