# Generated by Django 4.1.1 on 2023-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_users_alter_stock_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='EMAIL', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='PASSWORD', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='USERNAME', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='FIRST NAME', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='LAST NAME', max_length=15),
        ),
    ]
