# Generated by Django 4.1.1 on 2023-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_users_email_users_password_users_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
